"""Create clients table and fix audio file types

Revision ID: 1ceb468ddaa9
Revises: 7a728f6c6b80
Create Date: 2025-06-18 11:06:34.307494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ceb468ddaa9'
down_revision: Union[str, None] = '7a728f6c6b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(length=255), nullable=False),
    sa.Column('partita_iva', sa.String(length=11), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pec', sa.String(length=255), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('rappresentante_legale', sa.String(length=255), nullable=True),
    sa.Column('cf_rappresentante', sa.String(length=16), nullable=True),
    sa.Column('settore_attivita', sa.String(length=100), nullable=True),
    sa.Column('numero_dipendenti', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('documents_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('verbs_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbs_id'), 'verbs', ['id'], unique=False)
    op.drop_index('ix_transcriptions_summaries_id', table_name='transcriptions_summaries')
    op.drop_table('transcriptions_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name='transcriptions_summaries_transcript_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transcriptions_summaries_pkey')
    )
    op.create_index('ix_transcriptions_summaries_id', 'transcriptions_summaries', ['id'], unique=False)
    op.drop_index(op.f('ix_verbs_id'), table_name='verbs')
    op.drop_table('verbs')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
