"""Fix blob size for audio file_data

Revision ID: c1561f69e802
Revises: fd8370d1b2ab
Create Date: 2025-06-11 16:28:02.788406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1561f69e802'
down_revision: Union[str, None] = 'fd8370d1b2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 'file_data',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 'file_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
